### ISSUE TITLE
Issue with quantity of items in pocket

### ISSUE THREAD

**Issue by NinFanBoyFTW** [Cuyler36/MyHorizons#11]
Hi. First I just wanted to say, I love the program. I really appreciate how much functionality is in it already and I am loving this game so much more now. Please keep up the good work.

Onto my issue. I noticed that after I added one item to my pocket, almost all of my items in my pocket with multiple quantities such as resources or fruit went from whatever quantity I had before (Example: 20 apples) down to only 1 of each item. Obviously this isn't a deal breaker right now because I can always add back things I lost like additional gold pieces, but again, currently, after editing your bag items, the quantity is changed

Also this would be more of a feature request but I guess I was wondering if you are able to add an option to change the quantity of items currently in storage. Currently all I saw with storage editing was replacing the items currently in a particular spot and not viewing and editing the quantity of an item

Thanks again, and keep up the great work

**Comment by Cuyler36** [comment]
This was fixed in an earlier commit. Please rebuild from master.

**Comment by NinFanBoyFTW** [comment]
Ok thank you. Is there a way to edit the quantity of each item

Edit: Sorry and also is there is simple explanation of what the different flags variables are for

**Comment by Cuyler36** [comment]
The Flag2 value is one of the following:
- Count for items that can be stacked
- Customization setting for furniture items
- DIY Recipe ID for the DIY Recipe item

There are probably more. Flag2 so far always seems to be a number value and not actual flags.

**Comment by NinFanBoyFTW** [comment]
Ok, for items that can be stacked, is flag 2 the number of additional items stacked on the first item, because I have 2 gold pieces right now and flag 2 for that item only says 1

**Comment by Cuyler36** [comment]
Yes, for those items, it starts at 0 for 1. Since the maximum value it can hold is 0xFF (255), the max number of items in a stack is 255 + 1, or 256.

**Comment by NinFanBoyFTW** [comment]
Ok great. Thanks for clearing that up for me. Again keep up the great work
