### ISSUE TITLE
issue with wallet editing

### ISSUE THREAD

**Issue by NinFanBoyFTW** [Cuyler36/MyHorizons#12]
Hi. Another problem i'm having is that the wallet bells editing seem to not work correctly for me. Currently I have 88,749 bells in my wallet, but in MyHorizons I only see 2900. Also Whenever I edit this number, it seems to wipe out the bells in my wallet. Thanks again

**Comment by Silly-Aussie** [comment]
The wallet isn’t working properly for me either. I emptied my wallet just to check, yet it said 18900. And changing it didn’t do anything.

**Comment by Cuyler36** [comment]
I'll look into it. There's probably more to the wallet than we know.
