### ISSUE TITLE
Latest commit cant open files

### ISSUE THREAD

**Issue by ObscenityIB** [Cuyler36/MyHorizons#14]
![image](https://user-images.githubusercontent.com/6983255/78088526-21960500-7410-11ea-8d28-eb03eb2e2545.png)

**Comment by Cuyler36** [comment]
That's an issue with Windows not being able to find a DLL required to show the native file selector dialog window. It's not something caused by MyHorizons. Try forcing it to run as 32-bit by adding an x86 CPU configuration. If it's not that, then there's an issue with AvaloniaUI and your system.

**Comment by Cuyler36** [comment]
Update on this: It appears to be an issue with IDelegateFolder. It could be due to an anti-virus blocking  file access from MyHorizons. Can you try to disable your AV or allow MyHorizons through it and see if it works then?

**Comment by ObscenityIB** [comment]
Same issue happens when explicitly setting the target to x86
My antivirus is CommonSense™.

**Comment by silentdragonz** [comment]
I had the same issue when trying to access the file directly from my SD card reader. I copied the file to an internal drive first and then it worked.

**Comment by Cuyler36** [comment]
Interesting. It's probably a bug with AvaloniaUI then. I'll see if I can ask them about it. For now try to keep your files on your main drive when editing them.

**Comment by ObscenityIB** [comment]
> 
> 
> I had the same issue when trying to access the file directly from my SD card reader. I copied the file to an internal drive first and then it worked.

this worked perfectly, thanks

@Cuyler36 thanks for your development efforts too, this tool is excellent for those of us who cant go online.
