### ISSUE TITLE
Option To Modify/Change Passport Image?

### ISSUE THREAD

**Issue by MirayXS** [Cuyler36/MyHorizons#29]
Hello! I have an enhancement for the save editor you could consider.
When clicking the image for the passport, or right-clicking it, a option named "Change/Modify Image" should appear that will change the passport image. When clicking on it, it will open a file explorer page to select the image to modify the passport.
I'm not sure if this is modifiable or editable in any way..

**Comment by untuned** [comment]
It's modifiable, but doing so **will** get you banned from online. It won't be added to the editor for this reason.

**Comment by MirayXS** [comment]
> It's modifiable, but doing so **will** get you banned from online. It won't be added to the editor for this reason.

Ah ok, well that’s a rip. Thanks for replying

**Comment by igromanru** [comment]
What? Any cheating and save editing can get you banned online.   
Don't play online if you cheat.
That's not a reason for me to let the feature out.
