### ISSUE TITLE
Sorry,not this issues,but why i edit my personal.dat then crashed

### ISSUE THREAD

**Issue by limoonfeat** [Cuyler36/MyHorizons#3]
I decrytpted my save by using horizonCrypte,
then i edit the personal.dat by HxD and search item code and change it like 3308 to 7e21 
after all ,start the game but it said savedata crashed? 
are there something i missed?

**Comment by Aria-NL** [comment]
Why is this issue here and not at the HorizonCrypt issues page? https://github.com/Cuyler36/HorizonCrypt/issues

**Comment by limoonfeat** [comment]
I think savedata editing is not the Horizoncrypt issues?
savedata encrypted successfully ，problem is why the edited data can not be used？

**Comment by Cuyler36** [comment]
HorizonCrypt has not been updated to support 1.1.1. It has the same bug that MyHorizons had. I didn't fix it because MyHorizons supersedes HorizonCrypt.

**Comment by limoonfeat** [comment]
OH I see，and thank you very much for these nice work！
