### ISSUE TITLE
Villager/item list is very hard to scroll through.

### ISSUE THREAD

**Issue by Aria-NL** [Cuyler36/MyHorizons#6]
At the moment, the list of villagers and items is super long and unsearchable. It may be prudent to make the dropdown menu typeable - as in, if you start typing the name of a villager or item, it narrows it down to matching results. At the moment the easiest way of finding a villager or item is to go into the two txt files and doing Ctrl-F. Additionally, is there a way to include the recipes for DIY items in the list as well as the item itself?

**Comment by Cuyler36** [comment]
DIY Recipes are all one item with their Flag2 set to the DIY Recipe ID. You can edit it like that using the latest commit.

As for searching the item list -- I agree. AvaloniaUI appears to have renamed their "DropDownMenu" to "ComboBox" and never implemented the IsEditable functionality (meaning searching for items is super annoying). I'll look into a way to fix this. Perhaps I'll add an ItemId TextBox.

**Comment by Yokixio** [comment]
How to use the flag2

**Comment by 424778940z** [comment]
Have the same issue, maybe just make the list box longer for now, so it's easier to look through.

**Comment by 424778940z** [comment]
Made an ugly workaround for now, but hey, it works.
Code available here: https://github.com/424778940z/MyHorizons/commit/aa3a34429e9faa581d14d5fc5ae34ca959963267
