### ISSUE TITLE
unintended changes + wallet

### ISSUE THREAD

**Issue by Silly-Aussie** [Cuyler36/MyHorizons#7]
I added some things to my inventory, and when I checked, customization I had done was removed, other items with variations were changed, and all supplies & fruit were single instead of stacks.
This happened even when I only edited an upcoming villager, staying away from the inventories.
![1 unedited](https://user-images.githubusercontent.com/24382301/77918716-fb754580-72e7-11ea-854e-01283be98326.jpg)
![1 edited](https://user-images.githubusercontent.com/24382301/77918708-fa441880-72e7-11ea-8cbf-179fcb718c47.jpg)
![2 unedited](https://user-images.githubusercontent.com/24382301/77918726-fd3f0900-72e7-11ea-8d75-0968cd823d93.jpg)
![2 edited](https://user-images.githubusercontent.com/24382301/77918722-fc0ddc00-72e7-11ea-8b6a-eb3bf8acb931.jpg)
![6 unedited](https://user-images.githubusercontent.com/24382301/77918728-fdd79f80-72e7-11ea-9b71-76c2481e6737.jpg)
![6 edited](https://user-images.githubusercontent.com/24382301/77918727-fdd79f80-72e7-11ea-84de-3c7385d13855.jpg)
![7 unedited](https://user-images.githubusercontent.com/24382301/77921988-2eb9d380-72ec-11ea-9678-562d47888bcd.jpg)
![7 edited](https://user-images.githubusercontent.com/24382301/77921994-2feb0080-72ec-11ea-8766-1b04b5ce32e2.jpg)

Also, the field for changing the wallet is wrong. It said I had about 10,000 here and didn't change when edited. NookMiles and Bank work fine though
![wallet  unedited](https://user-images.githubusercontent.com/24382301/77919649-2f9d3600-72e9-11ea-87ad-0efb8816d491.jpg)
![wallet edited](https://user-images.githubusercontent.com/24382301/77919815-62472e80-72e9-11ea-9266-dde0976e6162.jpg)

**Comment by Silly-Aussie** [comment]
I uploaded a zip with the edited and unedited saves to google drive in case you need them
https://drive.google.com/file/d/1Ny2b5D28gV1KSsFCkkGt1NUvPQChxaEB/view?usp=sharing

**Comment by Cuyler36** [comment]
I'll look into what you're saying about the wallet later, however it worked properly for me last time.

**Comment by Cuyler36** [comment]
I cannot reproduce the issue you were having with the wallet. Changes seem to be working fine for me.
